### ISSUE TITLE
Сборка дистрибутива обновления

### ISSUE THREAD

**Issue by realMaxA** [oscript-library/packman#16]
На данный момент не предусмотрена возможность создания дистрибутива обновления.

**Comment by EvilBeaver** [comment]
Предусмотрена. Может не работать, не проверял, но предусмотрена.

**Comment by realMaxA** [comment]
Что значит "предусмотрена"?
Дистрибутив обновления создаётся при помощи ключа запуска 1С "-Option" (https://its.1c.ru/db/v8310doc#bookmark:adm:TI000000498), который в packman'е отсутствует как класс.

**Comment by realMaxA** [comment]
Я уже сделал PR на этот счёт.

**Comment by EvilBeaver** [comment]
А, это да. Я имел в виду именно Обновление, т.е. сборку cfu относительно предыдущих версий

**Comment by EvilBeaver** [comment]
Эту закрываю, новую открываю https://github.com/oscript-library/packman/issues/20
