### ISSUE TITLE
Документация

### ISSUE THREAD

**Issue by Infactum** [oscript-library/packman#2]
Проект часто упоминается в вебинарах, при этом вменяемая документация отсутствует.
Описание возможностей на главной тоже видимо не актуально, т.к. например формирование CFU было заявлено на вебинаре.

**Comment by JohnyDeath** [comment]
Вы так написали, как будто купили продукт с годовой подпиской.
Вам просто так отдали крутой инструмент. Если кажется, что в нем плохо сделана документация, то есть возможность вам самим взять и написать ее такой, какой вы ее хотели бы видеть. Благо исходники открыты и написаны на всем нам известном диалекте.

**Comment by Infactum** [comment]
@JohnyDeath 
Хорошо однако, что разработчик не вы. С таким отношением никто ваш продукт бы развивать не стал.
У меня логика простая:
1. Услышал про продукт
2. Посмотрел что описания толком нет, но зная, что разработчик всячески пропагандирует BDD, изучил feature файл.
3. Нужного мне функционала там не увидел и про проект забыл.
4. Получил от разработчика на вебинаре инфу, что таки нужный функционал таки должен присутствовать..
5. Зафиксировал фидбэк.

**Comment by EvilBeaver** [comment]
Женя так реагирует, просто потому что бывают деятели не очень вменяемые. Спасибо за фиксацию задачи! :)
