### ISSUE TITLE
Сонар обнаружил множество критичных проблем в коде

### ISSUE THREAD

**Issue by artbear** [oscript-library/packman#25]
[Ссылка на критичные проблемы packman в Сонаре](https://sonar.silverbulleters.org/code?id=oscript-lib-full&selected=oscript-lib-full%3Apackman%2Fsrc)

**Comment by nixel2007** [comment]
Эээ... Регистр ключевого слова и магическое число. Где критичные проблемы-то?

**Comment by artbear** [comment]
я ссылку слишком общую (для общего каталога проекта) приложил :(
более детальная правильная ссылка с проблемами https://sonar.silverbulleters.org/code?id=oscript-lib-full&selected=oscript-lib-full%3Apackman%2Fsrc%2F%D0%9A%D0%BB%D0%B0%D1%81%D1%81%D1%8B

**Comment by artbear** [comment]
Сплошные "Добавьте Возврат в функцию" :)
Типовая ошибка для 1С.

ps как я рад, что мы добавили это правило в Сонар!

**Comment by nixel2007** [comment]
Если что - страница конкретной папки packman/src/Классы - https://sonar.silverbulleters.org/dashboard?id=oscript-lib-full%3Apackman%2Fsrc%2F%D0%9A%D0%BB%D0%B0%D1%81%D1%81%D1%8B

**Comment by artbear** [comment]
Удобно. Не знал о таки ссылках.
А как-то из веб-интерфейса самого Сонара такую ссылку получить можно?

**Comment by nixel2007** [comment]
![sonar](https://user-images.githubusercontent.com/1132840/35471063-898cf740-0365-11e8-97c6-9e8b476bd89e.gif)
