### ISSUE TITLE
Проблема загрузки файлов в packman

### ISSUE THREAD

**Issue by EZSuleyman** [oscript-library/packman#36]
При загрузке файлов packman-ом через команду packman load-src (путь), выдает ошибку:
ОШИБКА - Получен ненулевой код возврата 1. Выполнение скрипта остановлено!
КРИТИЧНАЯОШИБКА - {Модуль C:\Program Files (x86)\OneScript\lib\v8runner\src\v8runner.os /ошибка в строке: 1388 / Неизвестная версия формата 2.9 загружаемого файла (Путь к файлам\Configuration.xml)
}
При выгрузке файлов на платформе <= 8.3.14 где версия ConfigDumpInfo и Configuration <= 2.8 все работает нормально 
Скрин прилагаю 
![packman error](https://user-images.githubusercontent.com/57996937/85830846-f2d0c600-b795-11ea-9bd2-4751090a1ffa.png)

**Comment by 240596448** [comment]
Вы загружаете файлы от 8.3.15 в 8.3.14.
Это вывод ошибки от 1С.
Решение: использовать 8.3.15+

**Comment by artbear** [comment]
закрываю, т.к.. причина не в пакман. 

Автор, переоткрывайте, если считаете иначе.
