### ISSUE TITLE
Вебинар на ИС уже не бесплатный.

### ISSUE THREAD

**Issue by VolAll** [oscript-library/packman#38]
Есть бесплатный вебинар Открытый инструментарий счастливого 1С-ника
http://infostart.ru/webinars/564258/

доступ: Ошибка! К сожалению доступ к указанному вебинару ограничен

**Comment by EvilBeaver** [comment]
А что вы предлагаете? Вебинар - собственность ИС. Тем более, что стоит недорого.

**Comment by nixel2007** [comment]
Думаю, речь про Readme. Убрать оттуда слово "бесплатный"

**Comment by artbear** [comment]
на ютубе бесплатно https://www.youtube.com/watch?v=RuFXBLzch2o&ab_channel=INFOSTART.RU
