### ISSUE TITLE
Команда clear-workspace

### ISSUE THREAD

**Issue by EvilBeaver** [oscript-library/packman#4]
Нужно уметь чистить временную базу, создаваемую в цикле сборки.

**Comment by artbear** [comment]
Что значит "чистить"? просто удалять каталог? или что-то еще?

**Comment by artbear** [comment]
ИМХО название и содержание команды расходятся :(
Название "Очищает рабочий каталог packman", содержание - в этом каталоге удаляются только txt-файлы.
Будет путаница :(
