### ISSUE TITLE
Исключение при выполнении packman help

### ISSUE THREAD

**Issue by Tur8008** [oscript-library/packman#7]
Добрый день, с новым годом коллеги. Спасибо за Ваш труд, очень радуют Ваши проекты!

Поставил packman через opm install. При исполнении команды packman help получаю следующее:

КРИТИЧНАЯОШИБКА - {Модуль C:\Program Files (x86)\OneScript\lib\packman\
 в строке: 33 / Метод объекта не обнаружен (ВывестиСправкуПоКомандам)}

**Comment by IslamA** [comment]
@Tur8008 попробуйте переустановить OneScript.

**Comment by nixel2007** [comment]
Попробуйте обновить opm и cmdline

`opm install opm`
`opm install cmdline`

Если на первую команду ругнется (что opm уже установлен) , то вместо install наберите update. В последних релизах опм это уже убрано.

**Comment by Tur8008** [comment]
Обновил с версии 14 до 15-й и все заработало. Спасибо!
